# bcm-asic-service package

BCM_ASIC_SERVICE_VERSION = 0.1

export BCM_ASIC_SERVICE_VERSION

BCM_ASIC_SERVICE = bcm-asic-service_$(BCM_ASIC_SERVICE_VERSION)_$(CONFIGURED_ARCH).deb
# $(BCM_ASIC_SERVICE)_DEPENDS += $(NET_MIDDLEWARE) $(OPENBCM)
# $(BCM_ASIC_SERVICE)_RDEPENDS += $(NET_MIDDLEWARE) $(OPENBCM)
$(BCM_ASIC_SERVICE)_SRC_PATH = $(SRC_PATH)/BcmAsicService

SONIC_DPKG_DEBS += $(BCM_ASIC_SERVICE)

export BCM_ASIC_SERVICE
