# bcmasicd package

BCMASICD_VERSION = 6.5.21

export BCMASICD_VERSION

BCMASICD = bcmasicd_$(BCMASICD_VERSION)_$(CONFIGURED_ARCH).deb
$(BCMASICD)_DEPENDS += $(NET_MIDDLEWARE)
# $(BCMASICD)_RDEPENDS += $(OPENBCM)
$(BCMASICD)_SRC_PATH = $(SRC_PATH)/bcmasicd

SONIC_DPKG_DEBS += $(BCMASICD)

export BCMASICD
