# docker image for bcm-asic-service

DOCKER_BCM_ASIC_SERVICE_STEM = docker-sonic-bcm-asic-service
DOCKER_BCM_ASIC_SERVICE = $(DOCKER_BCM_ASIC_SERVICE_STEM).gz

$(DOCKER_BCM_ASIC_SERVICE)_DEPENDS += $(NET_MIDDLEWARE) $(OPENBCM)

$(DOCKER_BCM_ASIC_SERVICE)_PATH = $(DOCKERS_PATH)/$(DOCKER_BCM_ASIC_SERVICE_STEM)

$(DOCKER_BCM_ASIC_SERVICE)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BULLSEYE)

$(DOCKER_BCM_ASIC_SERVICE)_VERSION = 1.0.0
$(DOCKER_BCM_ASIC_SERVICE)_PACKAGE_NAME = bcm-asic-service

ifeq ($(INCLUDE_BCM_ASIC_SERVICE), y)
SONIC_DOCKER_IMAGES += $(DOCKER_BCM_ASIC_SERVICE)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_BCM_ASIC_SERVICE)
endif

$(DOCKER_BCM_ASIC_SERVICE)_CONTAINER_NAME = bcm-asic-service
$(DOCKER_BCM_ASIC_SERVICE)_RUN_OPT += -t --cap-add NET_ADMIN --privileged
$(DOCKER_BCM_ASIC_SERVICE)_RUN_OPT += -v /dev:/dev
$(DOCKER_BCM_ASIC_SERVICE)_RUN_OPT += -v /var/run/redis/redis.sock:/var/run/redis/redis.sock
$(DOCKER_BCM_ASIC_SERVICE)_RUN_OPT += -v /lib/modules:/lib/modules:ro
$(DOCKER_BCM_ASIC_SERVICE)_RUN_OPT += --network=host -p=50052:50052/tcp

$(DOCKER_BCM_ASIC_SERVICE)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)
