# docker image for net-middleware

DOCKER_NET_MIDDLEWARE_STEM = docker-sonic-net-middleware
DOCKER_NET_MIDDLEWARE = $(DOCKER_NET_MIDDLEWARE_STEM).gz

$(DOCKER_NET_MIDDLEWARE)_DEPENDS += $(JSON_SCHEMA_VALIDATOR) $(NET_MIDDLEWARE)

$(DOCKER_NET_MIDDLEWARE)_PATH = $(DOCKERS_PATH)/$(DOCKER_NET_MIDDLEWARE_STEM)

$(DOCKER_NET_MIDDLEWARE)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BULLSEYE)

$(DOCKER_NET_MIDDLEWARE)_VERSION = 1.0.0
$(DOCKER_NET_MIDDLEWARE)_PACKAGE_NAME = net-middleware

ifeq ($(INCLUDE_NET_MIDDLEWARE), y)
SONIC_DOCKER_IMAGES += $(DOCKER_NET_MIDDLEWARE)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_NET_MIDDLEWARE)
endif

$(DOCKER_NET_MIDDLEWARE)_CONTAINER_NAME = net-middleware
$(DOCKER_NET_MIDDLEWARE)_RUN_OPT += -t --cap-add NET_ADMIN --privileged
$(DOCKER_NET_MIDDLEWARE)_RUN_OPT += -v /var/run/redis/redis.sock:/var/run/redis/redis.sock
$(DOCKER_NET_MIDDLEWARE)_RUN_OPT += -v /etc/sonic/credentials:/etc/sonic/credentials:ro
$(DOCKER_NET_MIDDLEWARE)_RUN_OPT += --network=host -p=8000:8000/tcp

$(DOCKER_NET_MIDDLEWARE)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)
