# docker image for bcmasicd

DOCKER_BCMASICD_STEM = docker-sonic-bcmasicd
DOCKER_BCMASICD = $(DOCKER_BCMASICD_STEM).gz

$(DOCKER_BCMASICD)_DEPENDS += $(JSON_SCHEMA_VALIDATOR) $(BCMASICD)

$(DOCKER_BCMASICD)_PATH = $(DOCKERS_PATH)/$(DOCKER_BCMASICD_STEM)

$(DOCKER_BCMASICD)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BULLSEYE)

$(DOCKER_BCMASICD)_VERSION = 1.0.0
$(DOCKER_BCMASICD)_PACKAGE_NAME = bcmasicd

ifeq ($(INCLUDE_BCMASICD), y)
SONIC_DOCKER_IMAGES += $(DOCKER_BCMASICD)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_BCMASICD)
endif

$(DOCKER_BCMASICD)_CONTAINER_NAME = bcmasicd
$(DOCKER_BCMASICD)_RUN_OPT += --privileged
$(DOCKER_BCMASICD)_RUN_OPT += -t
$(DOCKER_BCMASICD)_RUN_OPT += -v /var/run/redis/redis.sock:/var/run/redis/redis.sock
$(DOCKER_BCMASICD)_RUN_OPT += -v /etc/sonic/credentials:/etc/sonic/credentials:ro
$(DOCKER_BCMASICD)_RUN_OPT += --network=host

$(DOCKER_BCMASICD)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)
