# docker image for flexconfig

DOCKER_FLEXCONFIG_STEM = docker-sonic-flexconfig
DOCKER_FLEXCONFIG = $(DOCKER_FLEXCONFIG_STEM).gz

$(DOCKER_FLEXCONFIG)_DEPENDS += $(JSON_SCHEMA_VALIDATOR) $(FLEXCONFIG)

$(DOCKER_FLEXCONFIG)_PATH = $(DOCKERS_PATH)/$(DOCKER_FLEXCONFIG_STEM)

$(DOCKER_FLEXCONFIG)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BULLSEYE)

$(DOCKER_FLEXCONFIG)_VERSION = 1.0.0
$(DOCKER_FLEXCONFIG)_PACKAGE_NAME = flexconfig

ifeq ($(INCLUDE_FLEXCONFIG), y)
SONIC_DOCKER_IMAGES += $(DOCKER_FLEXCONFIG)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_FLEXCONFIG)
endif

$(DOCKER_FLEXCONFIG)_CONTAINER_NAME = flexconfig
$(DOCKER_FLEXCONFIG)_RUN_OPT += -t
$(DOCKER_FLEXCONFIG)_RUN_OPT += -v /var/run/redis/redis.sock:/var/run/redis/redis.sock
$(DOCKER_FLEXCONFIG)_RUN_OPT += -v /etc/sonic/credentials:/etc/sonic/credentials:ro
$(DOCKER_FLEXCONFIG)_RUN_OPT += -p=8001:8001/tcp

$(DOCKER_FLEXCONFIG)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)
