# flexconfig package

FLEXCONFIG_VERSION = 0.1

export FLEXCONFIG_VERSION

FLEXCONFIG = flexconfig_$(FLEXCONFIG_VERSION)_$(CONFIGURED_ARCH).deb
$(FLEXCONFIG)_DEPENDS += $(JSON_SCHEMA_VALIDATOR)
$(FLEXCONFIG)_RDEPENDS += $(JSON_SCHEMA_VALIDATOR)
$(FLEXCONFIG)_UNINSTALLS = $(JSON_SCHEMA_VALIDATOR)
$(FLEXCONFIG)_SRC_PATH = $(SRC_PATH)/FlexConfig
# SONIC_MAKE_DEBS += $(FLEXCONFIG)

SONIC_DPKG_DEBS += $(FLEXCONFIG)

export FLEXCONFIG
