# netmiddleware package

NET_MIDDLEWARE_VERSION = 0.1

export NET_MIDDLEWARE_VERSION

NET_MIDDLEWARE = net-middleware_$(NET_MIDDLEWARE_VERSION)_$(CONFIGURED_ARCH).deb
$(NET_MIDDLEWARE)_DEPENDS += $(JSON_SCHEMA_VALIDATOR)
$(NET_MIDDLEWARE)_RDEPENDS += $(JSON_SCHEMA_VALIDATOR)
# $(NET_MIDDLEWARE)_UNINSTALLS = $(JSON_SCHEMA_VALIDATOR)
$(NET_MIDDLEWARE)_SRC_PATH = $(SRC_PATH)/NetMiddleware
# SONIC_MAKE_DEBS += $(NET_MIDDLEWARE)

SONIC_DPKG_DEBS += $(NET_MIDDLEWARE)

export NET_MIDDLEWARE
